/**
 * 配置服务API
 * 配置服务API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { Config } from './config';
import { CursorExtra } from './cursorExtra';

export class InlineResponse2004Data {
    'extra'?: CursorExtra;
    'items'?: Array<Config>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "extra",
            "baseName": "extra",
            "type": "CursorExtra"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<Config>"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2004Data.attributeTypeMap;
    }
}

