/**
 * 配置服务API
 * 配置服务API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { SortSpec } from './sortSpec';

export class PageQuery {
    /**
    * 查询条件，传键值对
    */
    'filters'?: object;
    /**
    * 页码
    */
    'pageNo'?: number;
    /**
    * 每页数据量
    */
    'pageSize'?: number;
    /**
    * 排序
    */
    'sort'?: Array<SortSpec>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "filters",
            "baseName": "filters",
            "type": "object"
        },
        {
            "name": "pageNo",
            "baseName": "pageNo",
            "type": "number"
        },
        {
            "name": "pageSize",
            "baseName": "pageSize",
            "type": "number"
        },
        {
            "name": "sort",
            "baseName": "sort",
            "type": "Array<SortSpec>"
        }    ];

    static getAttributeTypeMap() {
        return PageQuery.attributeTypeMap;
    }
}

