/**
 * 配置服务API
 * 配置服务API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class SortSpec {
    /**
    * 排序字段
    */
    'property'?: string;
    /**
    * 排序类型，0默认，1升序，2降序
    */
    'type'?: string;
    /**
    * 是否忽略大小写
    */
    'ignoreCase'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "property",
            "baseName": "property",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "ignoreCase",
            "baseName": "ignoreCase",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SortSpec.attributeTypeMap;
    }
}

